[project]
name = "kenny-pdm-hangman"
version = "0.1.0"
description = "Python Hangman Game"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "bpython>=0.25",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
]
